### ISSUE TITLE
[he.encode] Avoid error if arg string is null

### ISSUE THREAD

**Issue by lyrad** [mathiasbynens/he#26]
Hi, good library! 
But I don't want to test if my string is null or not before to he.encode it (lazy boy :)).
The strings coming from left jointed sql requests are often null...

So I add, line 139, just after "var encode = function(string, options) { ...  "
    if(string === null)return '';

**Comment by catmeme** [comment]
This tip helped me out. I wrote my wrapper as such. I'm sure it could be consolidated but thought it might help someone else as is:

```js
function isInt(value) {
  return !isNaN(value) &&
         parseInt(Number(value)) == value &&
         !isNaN(parseInt(value, 10));
}

function isFloat(n) {
    return Number(n) === n && n % 1 !== 0;
}

// Add encodeall method to avoid potential issues
he.encodeall = function(string, opt) {
  if (string === null) {
    return "";
  } else if (isInt(string) || isFloat(string)) {
    return string;
  } else {
    return he.encode(string, opt)
  }
};
```

now I just use he as such: `he.encodeall(null)`
