### ISSUE TITLE
Ignore emojis

### ISSUE THREAD

**Issue by garrett-gottlieb** [mathiasbynens/he#33]
Is there a way to ignore emojis, like
```js
he.encode('You\'re so young 😏', { ignoreEmoji: true })
```

**Comment by mathiasbynens** [comment]
No. Why would you want to?

**Comment by anko** [comment]
Filter them yourself, maybe with [a regex](http://stackoverflow.com/questions/24840667/what-is-the-regex-to-extract-all-the-emojis-from-a-string?lq=1).

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/emoji-regex
