### ISSUE TITLE
SyntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by cyphix333** [mathiasbynens/he#37]
I'm trying to use this library but every time I include it (WordPress Project) I get the following error in the console in both FF & Chrome:

```
SyntaxError: expected expression, got '<'
http://******************************/js/he.js?ver=0.5.0
Line 32
```
Cheers!

**Comment by mathiasbynens** [comment]
I cannot reproduce the issue with the latest version from this GitHub repository. I guess your file somehow got mangled. Try getting a fresh copy.

**Comment by cyphix333** [comment]
Ok, seems I was using the wrong `he.js` file. I was using the one in `src` and not the one in the root dir. What is the difference?

Btw..... thanks for the excellent library!

**Comment by mathiasbynens** [comment]
The one in `src` contains placeholders for complex data that is generated and placed into the code at build time.

**Comment by cyphix333** [comment]
So which one should I be using? I tried the one in root but then I got..

```
he is not a function
```

My usage:

```
jQuery('input[name=billing_name]').val(he(name));
```

**Comment by cyphix333** [comment]
My bad, I see I missed using the `encode` part. *facepalm*

**Comment by mathiasbynens** [comment]
What are you trying to do exactly?

When using `jQuery#val()` there’s no need to HTML-encode first (unless you want to display the HTML-encoded value).

**Comment by cyphix333** [comment]
It's basically just a simple checkbox that populates the billing info the same as the applicant details. So I thought I would need to make sure the data pulled from the applicant data would be in entities to avoid breaking things if the values had certain characters such as backslashes.

**Comment by mathiasbynens** [comment]
Yeah, you don’t need `he` for that. Just set `.val()` directly.

**Comment by cyphix333** [comment]
Oh ok, thanks!
