### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by danhayden** [mathiasbynens/he#41]
I see that there hasn't been a release since Aug 24, 2014.
Any reason for this and will there be a release soon?

**Comment by mathiasbynens** [comment]
Why do you need a new release? There are no known bugs; the list of named character references in the HTML Standard hasn’t been updated; _he_ works as it should.

**Comment by danhayden** [comment]
Because anyone using this through npm will be using version 0.5.0 and therefore not able to take advantage of the work that has gone into the repo since Aug 24, 2014

**Comment by mathiasbynens** [comment]
@danhayden he.js hasn’t been updated since the latest release, except for some minor changes in comments: https://github.com/mathiasbynens/he/compare/6606d5dacd888c2cfd9a93dfd6b8b5be4a518c16...4a5f578117b4e1cbf3a7b3a803afe296247b3199#diff-ce323cf52d64a3057332cf3538ca8b2d

**Comment by danhayden** [comment]
I've just realised the the commits since version 0.5.0 only affect development use not production i.e. devDependencies etc, apologies.
