### ISSUE TITLE
`&#00;` leaks NULL character

### ISSUE THREAD

**Issue by RReverser** [mathiasbynens/he#43]
As per spec, number should be parsed before mapping against [the table](https://html.spec.whatwg.org/multipage/syntax.html#table-charref-overrides), so `&#00;` should be decoded just in the same way as `&#0;` / `&#x00;` / ..., that is, replaced with `\uFFFD`.

Currently it instead returns actual "unsafe" `\u0000` string.

**Comment by mathiasbynens** [comment]
Good catch! Closing in favor of #44.

**Comment by RReverser** [comment]
@mathiasbynens Well, it's just the issue for the PR. It would be auto-closed when PR is merged ;)
