### ISSUE TITLE
Internet Explorer 11 + Edge 12-13-14 JavaScript parsing issues

### ISSUE THREAD

**Issue by gnutix** [mathiasbynens/he#53]
Hello,

I'm using this library in production and get reports of JavaScript errors (in TrackJS.com) from IE & Edge browsers like: 

* Expected identifier, string or number
* Unterminated string constant
* Expected ':', '}' or ';'
* illegal character

And when I check the error file / line, it's sometimes in he.js, like here : 

![fireshot capture 7 - track_js error_ expected identifier _ - https___my trackjs com_details_bb01](https://cloud.githubusercontent.com/assets/310134/24353407/b3d0ba6e-12ed-11e7-92f4-19e13bf4cfa4.png)

And sometimes it's in other parts of the code (like in YUI library)... seems completely random, by the way : 

![fireshot capture 10 - track_js error_ expected _ - https___my trackjs com_details_09c](https://cloud.githubusercontent.com/assets/310134/24353434/cd9d8422-12ed-11e7-9061-20c2198f5ede.png)

![fireshot capture 11 - track_js error_ expected _ - https___my trackjs com_details_f53](https://cloud.githubusercontent.com/assets/310134/24353443/dd5c035c-12ed-11e7-97ba-7b19a5ad13a6.png)

![fireshot capture 12 - track_js error_ illegal character_ - https___my trackjs com_details_1a7](https://cloud.githubusercontent.com/assets/310134/24353445/df90b44c-12ed-11e7-97d6-e21386e1f38d.png)

The only idea I have would be that IE shits on himself when loading the very long JSON defined in he.js. Or maybe the fact that there's very long strings processed in regex ?

Here's the exact version of he.js I'm using in my project : [he.js.zip](https://github.com/mathiasbynens/he/files/872208/he.js.zip)
I've modified it a bit, trying to cut the very long lines into shorter lines. Which didn't fixed it.

Have you ever had any issue of this kind ?

Thanks a lot for your help.
gnutix

**Comment by mathiasbynens** [comment]
> Have you ever had any issue of this kind?

#40 sounds similar. It sounds like this issue only occurs randomly / sometimes — is that correct?
 Could you provide a reduced test case so I can easily verify the issue?

**Comment by gnutix** [comment]
Concerning #40, on my application there is only YUI code that is minified. All other vendors (incl he.js) and the application code is not.

I've never encountered it myself, as I'm on Linux and don't have IE11/Edge easily available and never (yet) went through the trouble of settting up VMs. According to the high number of visitors on the application and the low number of errors reported, and their random nature (in the error itself and the file/line it points to), I fear that it will be Mission Impossible to have a truly reproducible test case...

In the meantime, I've replaced he.js by a simple regex (even though I know the drawbacks), just to isolate if it's the source of the issue or not (might be YUI, or minified YUI, or even another piece of code...). Once I'll know for sure that it's caused by he.js, maybe I'll find the time to dig more into it (VMs and such)

**Comment by gnutix** [comment]
I've had the error again without he.js in the project! ... I've added it again.
Now let's see if YUI minified is the cause. I'll keep you posted just in case someone else, someday, as the same issue.

**Comment by mathiasbynens** [comment]
Much appreciated!

**Comment by gnutix** [comment]
I had two error reports even with non-minified JS... :( Guess I'll still have to find a solution. As it's not related to he.js, I've opened a question on stackoverflow : http://stackoverflow.com/questions/43044844/ie11-edge-12-13-14-random-javascript-parsing-errors-caused-by-very-long-obje
