### ISSUE TITLE
He.decode : keep some part encoded

### ISSUE THREAD

**Issue by mvuidev** [mathiasbynens/he#54]
Hi,

Using he.decode, I need to keep a part of the code encoded. Is it possible ?

For example, I do he.encode on : 

```
<h1>Title</h1>
<pre>
<p>Code</p>
</pre>
```

So I get : 

```
&lt;h1&gt;Title&lt;/h1&gt;
&lt;pre&gt;
&lt;p&gt;Code&lt;/p&gt;
&lt;/pre&gt;
```
And here is what I need to get doing a he.decode : 

```
<h1>Title</h1>
<pre>
&lt;p&gt;Code&lt;/p&gt;
</pre>
```

**Comment by mathiasbynens** [comment]
You’ll have to handle that yourself, outside of _he_. Parse the HTML and only encode/decode the parts you’re interested in.
