### ISSUE TITLE
How to download and use in app

### ISSUE THREAD

**Issue by arc95** [mathiasbynens/he#57]
Hi. Thanks for this great library. I'm having a challenge downloading this library and using it directly (not via npm). I downloaded `he.js` from [here](https://github.com/mathiasbynens/he/blob/master/src/he.js) but it seems to have other dependencies, as it errors on line 32 with `Unexpected token`:
```javascript
var encodeMap = <%= encodeMap %>;
```
Those `%` tags look like they belong server side. How do you download this library directly? What am I doing wrong? Thanks.

**Comment by mathiasbynens** [comment]
You need to use the built version at https://github.com/mathiasbynens/he/blob/master/he.js.

From CDNJS, for example: https://cdnjs.com/libraries/he

**Comment by arc95** [comment]
Thank you 👍
