### ISSUE TITLE
Representing `escape()` as `htmlEncode()`

### ISSUE THREAD

**Issue by sethimcclaine** [mathiasbynens/he#58]
Your site implies an html encoder, when it is really just escaping characters, not html encoding. 

https://mothereff.in/html-entities

**Comment by mathiasbynens** [comment]
In your interpretation, what does “HTML encoding” mean?

**Comment by sethimcclaine** [comment]
Encoding Characters that effect html in a way that they can be show in html. 

Thread: https://stackoverflow.com/questions/1219860/html-encoding-lost-when-attribute-read-from-input-field

**Comment by sethimcclaine** [comment]
Additional resources:

https://www.w3schools.com/html/html_entities.asp

http://php.net/manual/en/function.htmlentities.php

**Comment by mathiasbynens** [comment]
I’m confused… That’s exactly what `he.encode()` does: https://github.com/mathiasbynens/he#heencodetext-options
