### ISSUE TITLE
Syntax error in both Firefox and Chrome

### ISSUE THREAD

**Issue by arvindpdmn** [mathiasbynens/he#59]
Try to use this at client side. Console throws up an error.

Firefox:
`SyntaxError: expected expression, got '<'[Learn More]                   he.js:32:17`

Chrome:
`Uncaught SyntaxError: Unexpected token <          h2.js:32`

**Comment by mathiasbynens** [comment]
You’re using `src/he.js` instead of `he.js`.

**Comment by arvindpdmn** [comment]
Thanks.
