### ISSUE TITLE
Issue with pulling latest version 1.2.0

### ISSUE THREAD

**Issue by varun-dev** [mathiasbynens/he#69]
I am not sure if I am missing something, but the npm repository thinks `1.1.1` is the latest version.

![image](https://user-images.githubusercontent.com/359805/47560267-a9b8d680-d90f-11e8-9aa1-e2c7c535e9f1.png)

Refer to the response of this API
https://replicate.npmjs.com/he

**Comment by mathiasbynens** [comment]
![image](https://user-images.githubusercontent.com/81942/47570775-45117200-d937-11e8-86ec-e124a2c62b91.png)

**Comment by mathiasbynens** [comment]
https://www.npmjs.com/package/he looks alright for me.

Either way, this seems to be an npm issue, not a he issue.
