### ISSUE TITLE
Minified version?

### ISSUE THREAD

**Issue by timschwab** [mathiasbynens/he#70]
Is there a minified version or a CDN version that we can include in the browser? On your readme, I see the <script> include, but it'd be nice to have it all rolled up into a single minified file.

**Comment by mathiasbynens** [comment]
CDNJS hosts a copy, although they don’t serve it as UTF-8: https://cdnjs.com/libraries/he

https://github.com/cdnjs/cdnjs/issues/12756

**Comment by mathiasbynens** [comment]
Generally, if you need this in the browser, I’d expect you to add `he.js` to your existing build+minify process.

**Comment by styfle** [comment]
https://cdn.jsdelivr.net/npm/he@1.2.0/he.js

https://cdn.jsdelivr.net/npm/he@1.2.0/he.min.js

**Comment by mathiasbynens** [comment]
@styfle Interestingly, https://cdn.jsdelivr.net/npm/he@1.2.0/he.min.js says:

> Skipped minification because the original files appears to be already minified.

**Comment by styfle** [comment]
That is interesting  🤔 

I’m on my phone so I can’t tell if it’s actually minified already or a bug in jsdelivr.

**Comment by mathiasbynens** [comment]
It’s definitely not minified already.

**Comment by jimaek** [comment]
@MartinKolarik Can we fix the min detection here?

**Comment by MartinKolarik** [comment]
The file has some very long lines so we currently detect it as minified. I'll check if this could be improved.

**Comment by MartinKolarik** [comment]
We improved the detection of minified files and the above link serves a minified file now.

**Comment by mathiasbynens** [comment]
That answers it! Use [jsDelivr](https://www.jsdelivr.com/). 

```
https://cdn.jsdelivr.net/npm/he
https://cdn.jsdelivr.net/npm/he@1.2.0/he.min.js
```
