### ISSUE TITLE
Non-English support?

### ISSUE THREAD

**Issue by coderkind** [mathiasbynens/he#72]
Hi,

am I right in saying this doesn't support non-English text (such as Arabic)? It seems to be converted to entities when I try.

**Comment by mathiasbynens** [comment]
That’s what `he.encode` is supposed to do. From the README:

> ### `he.encode(text, options)`
>
> This function takes a string of text and encodes (by default) any symbols that aren’t printable ASCII symbols and `&`, `<`, `>`, `"`, `'`, and `` ` ``, replacing them with character references.
