### ISSUE TITLE
Unescape from HTML and escape to JSON

### ISSUE THREAD

**Issue by KaKi87** [mathiasbynens/he#73]
The HTML code I wanna convert is formatted as JSON.

My JSON string contains HTML entities inside properties values, and especially `&quot;`, which is the encoded character for `"`.

So, I need to escape the previously converted characters in JSON, which means adding a backslash (`\`) to them.

Thanks

**Comment by mathiasbynens** [comment]
Can you give an example?

Use `JSON.stringify()` to generate JSON (and take care of escaping quotes in strings).

**Comment by KaKi87** [comment]
> take care of escaping quotes in strings

That's exactly what I want to automate :)

**Comment by mathiasbynens** [comment]
Ok, I guess your issue is resolved then? :)

**Comment by KaKi87** [comment]
No because I didn't found out how to automate string quote escaping

**Comment by mathiasbynens** [comment]
I'm confused. I just told you that `JSON.stringify` does that for you.

**Comment by KaKi87** [comment]
`JSON.parse(JSON.stringify(val))` returns `val`

**Comment by mathiasbynens** [comment]
It does indeed!

Again, can you give an example of what you're trying to do? Provide example input, desired output, and code you've tried so far.

**Comment by KaKi87** [comment]
Here is a JSFiddle example : https://jsfiddle.net/KaKi87/56pbLtuf/

**Comment by mathiasbynens** [comment]
How is the content inserted into the `<pre>`? Are you doing that on the server side?

**Comment by KaKi87** [comment]
No, this is an example. 
The original is a real JSON response, fetched using NodeJS request.
But, this fiddle have the same behavior as in my script. The point is that I can't auto-escape quotes inside JSON strings.

**Comment by mathiasbynens** [comment]
> The original is a real JSON response, fetched using NodeJS request.

If it's a proper JSON response, then `JSON.parse` would succeed, making it different from the demo you shared.

I'm still struggling to understand what you mean.

**Comment by KaKi87** [comment]
Okay then try to parse this : https://trigedasleng.net/api/api?action=search&query=dei%20de

**Comment by mathiasbynens** [comment]
Works for me:

```js
(async () => {
  const response = await fetch('https://trigedasleng.net/api/api?action=search&query=dei%20de');
  const data = await response.json();
  console.log('Result:', data);
})();
// Result: {...}
```

**Comment by KaKi87** [comment]
Okay but did you decoded the HTML entities ?

**Comment by mathiasbynens** [comment]
To decode HTML entities in a string, [use `he.decode(string)`](https://github.com/mathiasbynens/he#hedecodehtml-options).

```js
(async () => {
  const response = await fetch('https://trigedasleng.net/api/api?action=search&query=dei%20de');
  const data = await response.json();
  data.words = data.words.map((word) => {
    word.translation = he.decode(word.translation);
    return word;
  });
  console.log('Result:', data);
})();
// Result: {...}
```

**Comment by KaKi87** [comment]
So, I must decode property by property ??

**Comment by mathiasbynens** [comment]
Yeah. There's no way `he` or any other library can know which values need decoding and which do not; it depends on the use case.

**Comment by KaKi87** [comment]
All I need is to automatically escape the `"` character

**Comment by David263** [comment]
It seems to me that you could use the string.replace method to replace any instance of " with \\" in your server strings (if that is truly "all you need"). The _he_ library is used to create and remove HTML entities, not to use \\ to escape characters in strings.
