### ISSUE TITLE
ASCII character 128 not being encoded by he

### ISSUE THREAD

**Issue by rakend** [mathiasbynens/he#75]
```
var _char = String.fromCharCode (128);
var got = he.encode (_char, {
  'encodeEverything': true
});
console.log (got);
alert (got);
```
When I run the above code snippet, I see a small square like character in both alert box and console instead of the encoded string. Is this like a special case or bug. I don't know how to fix this.

**Comment by mathiasbynens** [comment]
`128 === 0x80`, so this is `U+0080 <control> / Padding Character / PAD`.

And per [the spec](https://html.spec.whatwg.org/multipage/syntax.html#character-references):

> The numeric character reference forms described above are allowed to reference any code point excluding U+000D CR, noncharacters, and controls other than ASCII whitespace.

So this is working as intended.
