### ISSUE TITLE
Allow to ignore specific elements in the string, like code

### ISSUE THREAD

**Issue by lukasoppermann** [mathiasbynens/he#78]
Hey,

I would love an option to ignore certain parts of a string from decoding.

My use case is that I want to decode encoded html in a string, however there is also escaped html within a `code` element which I would like to not decode (as this will render it invisible).

I have no idea of how to do this with the current setup, is this possible, or could an option for this be added?

**Comment by evanjmg** [comment]
@lukasoppermann  find any solution for this? Running into the same thing.

**Comment by lukasoppermann** [comment]
Not really, but I am not actively using this package. Sorry.

**Comment by evanjmg** [comment]
@lukasoppermann found a solution DOMpurify does all of this and has tons of support. https://github.com/cure53/DOMPurify

**Comment by thetutlage** [comment]
Creating a custom rule is the way to go here. Maybe share it as a gist with others
